apiVersion: argoproj.io/v1alpha1 # ArgoCD Application resource
kind: Application               # Kind of resource
metadata:                        # Metadata section                         
  name: opentelemetry-argocd-app        # App name
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  namespace: argocd          # Must exist in ArgoCD namespace -ArgoCD only watches the argocd namespace by default.
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Sync order, lower numbers sync first
spec:
  project: opentelemetry-project         # Assigns app to the frontend-team Project
  source:
    repoURL: https://github.com/ashwinijadhav-aws/ultimate-devops-project-demo.git  # Git repo
    targetRevision: main        # Branch to watch
    path: kubernetes/ONESHOTDEPLOY/K8S-MANIFEST/    # Path in repo with manifests
  destination:
    server: https://kubernetes.default.svc # Target cluster, run `argocd cluster list` to see
    namespace: default          # Namespace inside that cluster
  syncPolicy:                    # Sync policy settings
    automated:                   # Enable automated sync
      prune: true                 # Delete resources removed from Git
      selfHeal: true              # Correct drift if resources change in cluster
    syncOptions:                 # Additional sync options
      - CreateNamespace=true      # Auto-create namespace if it doesn't exist